### ISSUE TITLE
Trouble with BuildTrajectory

### ISSUE THREAD

**Issue by margaret-ho** [BaderLab/Tempora#12]
Hello! 

I'm having some issues trying to run Tempora on my dataset.

I did the preprocessing on Seurat and integrated all of my samples using Harmony. I was able to calculate the pathway enrichment profiles of my clusters (gvsa method), but I received an error when trying to build the trajectory. Does this have something to do with genes that have constant expression being discarded in the previous step?

![Snip20201110_24](https://user-images.githubusercontent.com/74253032/98687211-79e29d00-2337-11eb-9008-6e5cf511c8ed.png)

Thank you!

**Comment by AmandaKedaigle** [comment]
I am having this same error. Did you ever find a solution?

**Comment by margaret-ho** [comment]
I'm still stuck on this! Please let me know if you figure anything out!

**Comment by thinh-tran** [comment]
Hi! Apologies for the late response. The error looks like it's due to the temporal scores for some clusters were not calculated properly in the previous step but Tempora did not throw an error message there to make sure it's corrected. Can you help me check this by running `your_tempora_object@cluster.metadata` in your R console and letting me know what it returns?

**Comment by AmandaKedaigle** [comment]
I think in my case it was because the cluster IDs were not integers. When I changed them all to be integers it is running successfully

**Comment by margaret-ho** [comment]
I fixed my cluster IDs and now it is running smoothly. Thank you!
