### ISSUE TITLE
readme.md comments

### ISSUE THREAD

**Issue by baj12** [BaderLab/Tempora#16]
A few comments/observations related to Readme.md:

Readme.md:
----------

need to load Seurat package

```cortex_tempora <- IdentifyVaryingPWs(cortex_tempora, pval_threshold = 0.05)```
return NULL if pval too low, i.e. erases all previous results.

Needed to change threshold from 0.05 to 0.5 to be able to run the example.

**Comment by risserlin** [comment]
Thanks for pointing that out.  I tried adding Seurat to the packages needed to import for Tempora but it didn't fullly install via that method so I I added the require Seurat package to the example.  

The p-value threshold of 0.5 sounds very high.  I am looking into it.

**Comment by risserlin** [comment]
So I looked into the p-value issue.  Can you check which pathway file you were using.  

I found that there was an issue with February_05_2021 and the January_11_2021, December_10_2020, and December_11_2020 files.  The standard GO_BP_AllPathways file only contained pathways databases and was missing GO_BP sets which means that they contained ~4000 pathways instead of +1900 pathways.  This was the reason that nothing was coming up as significant.  I have fixed the February_05_2021 files (and the generation code for future files).  (This was also an issue specific to mouse so wouldn't come out with the other example datasets for tempora)

**Comment by baj12** [comment]
works for me now.
Thx
